export const KILL_APP_LIST = [
	"Discord",
	"Slack",
	"Teams",
	"Zoom",
	"Webex",
	"KakaoTalk",
	"Skype",
	"Telegram",
	"WhatsApp",
	"LINE",
	"obs64",
	"bdcam",
	"XboxGameBar",
	"GameBarFTServer",
	"GameBar",
	"nvcontainer",
	"amddvr",
	"kalmuri",
	"EXCEL",
	"powerpnt",
	"winword",
	"hwp",
	"calculator",
	"Honeycam",
	"AllCap",
	"HanCapture",
	"SnippingTool",
	"Snipaste",
	"recorder",
	"recexperts",
	"flashbackrecorder",
	"facebookmessenger",
	"between",
	"teamviewer",
	"Bandicamera",
	"Google Chrome",
	"Chromium",
	"chrome",
	"Firefox",
	"Microsoft Edge",
	"edge",
	"Opera",
	"Brave",
	"Vivaldi",
	"iexplore",
	"safari",
	"whale",
	"PowerDirector", "DemoCreator", "DemoCreator Recorder", "DemoCreator Spark",
	"Recorder", "RelayRecorder",
	"BlueJeans",
	"VNC",
	"AnyDesk",
	"Chrome Legacy Window",
	"UltraViewer_Service",
	"UltraViewer_Desktop",
	"UltraViewer",
	"Mingleview",
	"Movavi",
	"OpenOffice",
	"ShareX", "ShareX64",
	"Free Snipping Tool",
	"Lightshot",
	"picpick",
	"Greenshot",
	"FastStoneCapture",
	"Screenpresso",
	"ScreenHunter",
	"Snagit",
	"CamtasiaStudio",
	"CamtasiaStudioEditor",
	"CamtasiaStudioRecorder",
	"CamtasiaRecorder",
	"ALCapture",
	"ALShow",
	"ALCaptureEditor",
	"nvsphelper64",
	"nvsphelper",
	"NVIDIA Share",
	"ShadowPlay",
	"NVIDIA GeForce Experience",
	"radeon"

];